DROP DATABASE IF EXISTS JokeRater;
CREATE DATABASE JokeRater;
USE JokeRater;
CREATE TABLE IF NOT EXISTS Users (Username VARCHAR(30) NOT NULL PRIMARY KEY, Password CHAR(32) NOT NULL, Favorite VARCHAR(300), Flagged VARCHAR(300));
CREATE TABLE IF NOT EXISTS Professors (ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, Name VARCHAR(100) NOT NULL);
CREATE TABLE IF NOT EXISTS Tags (ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, TagName VARCHAR(30));
CREATE TABLE IF NOT EXISTS Jokes (ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, Poster VARCHAR (100), Joke VARCHAR(200) NOT NULL, Class VARCHAR(20), Professor INT, Flagged BOOLEAN, Context VARCHAR(50), Funniness INT, Edginess INT, Punniness INT, Overall INT, TimeAdded TIMESTAMP);
CREATE TABLE IF NOT EXISTS AssJokes (ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY);

source C:/Users/norwa/Documents/NetBeansProjects/JokeRater/databaseSetup.sql